<?php
/**
 * Created by PhpStorm.
 * User: SKEPSIS-DEV40
 * Date: 2/9/2018
 * Time: 11:26 AM
 */

defined('_JEXEC')or die();

class HelloworldViewHelloworld extends \Joomla\CMS\MVC\View\HtmlView
{


    public function display($tpl = null)
    {
        $this->msg = 'Hello World from the view';
        return parent::display($tpl); // TODO: Change the autogenerated stub
    }
}