<?php
/**
 * Created by PhpStorm.
 * User: SKEPSIS-DEV40
 * Date: 2/6/2018
 * Time: 2:40 PM
 */

defined('_JEXEC') or die();

class HelloworldViewHelloworld extends \Joomla\CMS\MVC\View\HtmlView
{
    public function display($tpl = null)
    {
        //$this->msg = 'Hello World from the view';

        $this->msg = $this->get('Msg');

        if (count($errors = $this->get('Errors')))
        {
            JLog::add(implode('<br />', $errors), JLog::WARNING, 'jerror');

            return false;
        }

        return parent::display($tpl); // TODO: Change the autogenerated stub
    }
}