<?php
/**
 * Created by PhpStorm.
 * User: SKEPSIS-DEV40
 * Date: 2/6/2018
 * Time: 2:38 PM
 */

defined('_JEXEC') or die();

class HelloworldController extends \Joomla\CMS\MVC\Controller\BaseController
{

/*    public function display($cachable = false, $urlparams = array())
    {
        var_dump($this);
        return parent::display($cachable, $urlparams); // TODO: Change the autogenerated stub
    }

    public function special($cachable = false, $urlparams = array())
    {
        $this->getModel()->setResult("Result set from controller");
        //De aici nu mai stiu ... :(
    }*/
}