<?php
/**
 * Created by PhpStorm.
 * User: SKEPSIS-DEV40
 * Date: 2/9/2018
 * Time: 11:57 AM
 */
defined('_JEXEC') or die();

class HelloworldModelHelloworld extends \Joomla\CMS\MVC\Model\BaseDatabaseModel
{
    protected $message = array();

    public function getMsg()
    {
        $app = \Joomla\CMS\Factory::getApplication();
        $id = $app->input->get('id', 1, 'INT');

        $table = $this->getTable();

        $table->load($id);

        $this->message[$id] = $table->greeting;

        return $this->message[$id];
    }

    public function getTable($name = 'Helloworld', $prefix = 'HelloworldTable', $options = array())
    {
        return parent::getTable($name, $prefix, $options); // TODO: Change the autogenerated stub
    }
}