<?php
/**
 * Created by PhpStorm.
 * User: SKEPSIS-DEV40
 * Date: 2/13/2018
 * Time: 2:14 PM
 */

defined('_JEXEC') or die();

class HelloworldModelHelloworlds extends \Joomla\CMS\MVC\Model\ListModel
{
    protected function getListQuery()
    {
        $db = $this->getDbo();
        $query = $db->getQuery(true);

        $query->select('*')->from($db->qn('#__helloworld'));

        return $query;

        //return parent::getListQuery(); // TODO: Change the autogenerated stub
    }
}