<?php
/**
 * Created by PhpStorm.
 * User: SKEPSIS-DEV40
 * Date: 2/15/2018
 * Time: 3:34 PM
 */

defined('_JEXEC') or die();

class HelloworldControllerHelloworlds extends Joomla\CMS\MVC\Controller\BaseController
{
    public function delete()
    {
        $app = \Joomla\CMS\Factory::getApplication();
        $recs = $app->input->get('cid', array(), 'array');
        $nrecs = $app->input->get('boxchecked', 0, 'int');
        $model = $this->getModel('Helloworld', 'HelloworldModel');
        $model->delete($recs);
        $msg = "$nrecs record(s) deleted";
        $this->setRedirect(\Joomla\CMS\Router\Route::_('index.php?option=com_helloworld'),$msg);


        //parent::delete(); // TODO: Change the autogenerated stub
    }
}